#!/bin/sh

process() {
  local METHOD=$1
  local DATASET=$2
  echo == ${DATASET}
  ./wf ${METHOD} ${DATASET}
}

all() {
  local METHOD=$1

  process ${METHOD} data/abalone.csv
  process ${METHOD} data/banknotes.csv
  process ${METHOD} data/blood_samples_dataset_balanced.csv
  process ${METHOD} data/breast_cancer.csv
  process ${METHOD} data/crop_recommendation.csv
  process ${METHOD} data/diabetes_prediction_dataset.csv
  process ${METHOD} data/diabetes.csv
  process ${METHOD} data/diamond_buckets.csv
  process ${METHOD} data/diamond.csv
  process ${METHOD} data/heart_statlog_cleveland_hungary_final.csv
  process ${METHOD} data/iris.csv
  process ${METHOD} data/play_tennis.csv
  process ${METHOD} data/seeds_dataset.csv
  process ${METHOD} data/simple_weather.csv
  process ${METHOD} data/weather_classification_data.csv
  process ${METHOD} data/weather_forecast_data.csv
  process ${METHOD} data/wine.csv
}

all pure_random
all pure_balanced
all unique_random
all unique_balanced