#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH << './lib'

require 'opts'
require 'dataset'
require 'test'

o = Opts.new(ARGV)

source = o.option('--source', 'string')
function = o.option('--function', 'string')

s = Test.new.test(source, function)

puts format('[TEST] %s has a %.4f%% success rate', function, s)
